config/routes.rb
Cudi::Application.routes.draw do

  resources :cudidocs
  resources :pictures
  resources :filesuploads
   resources :photos, :only => [:create, :destroy]

  
  

devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :passwords => 'passwords' 
} do
  post '/users/sign_in' => 'sessions#create' 
  get  '/users/sign_out' => 'devise/sessions#destroy' 
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  
  resources :users

  resources :priorities

  resources :resources
  
  resources :proyectostatuses

  resources :historics

  resources :documents

  resources :uploads

  resources :panelcontrols, :path_names => { :update => 'updateroles' } 

	
  

 

  resources :panelcontrols,:only => [:generate_document] do
     collection do
       post "generate_document"
     end
   end

  resources :proyectos,:only => [:index] do
     collection do
       post "post_data"
     end
   end

  resources :proyectos,:only => [:editresources] do
     collection do
       post "editresources"
     end
   end

  resources :proyectos,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

  

  resources :proyectos,:only => [:new] do
     collection do
     end
   end

  resources :proyectos,:only => [:setg] do
     collection do
       post "setg"
     end
  end
   
   
  resources :proyectos,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
  end
   

   

  resources :proyectos,:only => [:list_proyect_iphone] do
     collection do
       post "list_proyect_iphone"
     end
   end
   
   

 

  resources :proyectos,:only => [:mobile_new_proyecto] do
     collection do
       get "mobile_new_proyecto"
       post "mobile_new_proyecto"
     end
   end
   

  resources :futureproyectos,:only => [:index] do
     collection do
       post "post_data_futureproyectos"
     end
   end
  
=begin
  resources :futureproyectos,:only => [:editresources] do
     collection do
       post "post_data_futureproyectosedit"
     end
  end
=end  

 
   
     resources :futureproyectosactions,:only => [:setg] do
     collection do
       post "setg"
     end
   end

  resources :proyectos,:only => [:pickupfile] do
     collection do
       post "pickupfile"
     end
   end
   

   

  resources :futureproyectosactions,:only => [:index] do
     collection do
       post "post_data_futureproyectosactions"
     end
   end
   
   
   resources :futureproyectosactions,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
    end
    
      resources :futureproyectosactions,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

   resources :cudidocs,:only => [:datasheetsave] do
     collection do
       post "datasheetsave"
     end
    end

   resources :cudidocs,:only => [:getHtml] do
     collection do
       post "getHtml"
     end
    end

   resources :cudidocs,:only => [:updatetitles] do
     collection do
       post "updatetitles"
     end
    end
    
    resources :cudidocs,:only => [:getalldocs] do
     collection do
       post "getalldocs"
     end
    end
    
    
    
    resources :cudidocs,:only => [:getallpublicdocs] do
     collection do
       post "getallpublicdocs"
     end
    end
    
    
    
    
       resources :cudidocs,:only => [:erasedocs] do
     collection do
       post "erasedocs"
     end
    end
    
     resources :cudidocs,:only => [:publicdocs] do
     collection do
       post "publicdocs"
     end
    end
    
     resources :cudidocs,:only => [:sendpdf] do
     collection do
       post "sendpdf"
     end
    end    
    
    
     resources :cudidocs,:only => [:enduserspreeadsheet] do
     collection do
       post "enduserspreeadsheet"
     end
    end   
     
    
    
    
    
    resources :users,:only => [:usersonline] do
         collection do
       post "usersonline"
     end
    end  
    
    
    
    

  
   match "listpdffiles" => "home#listpdffiles"
   match "showpdf" => "home#showpdf"
   
   match "cudidocs/getHtml/:docid" => "cudidocs#getHtml" 
   
   match "cudidocs/updatetitles/:noid" => "cudidocs#updatetitles"

  
  
  match "publicproyecto/:proyectotitle" => "publicproyecto#index" 
  
 
  
  match "sendpdftousers" => "panelcontrols#sendpdftousers"  
  match "create_pdf" => "panelcontrols#create_pdf" 
  match "proyectos/status/:status_id/resource/:resource_id" => "proyectos#index"
  match "futureproyectosactions/status/:status_id/resource/:resource_id" => "futureproyectosactions#index"
  
 
  match "futureproyectos/getresources"  => "futureproyectos#getresources"
  match "proyectos/publicos/:parent_id"  => "proyectos#proyectourl"
  match "proyectos/editresources/:parent_id"  => "proyectos#editresources"
  match "futureproyectos/editresources"  => "futureproyectos#editresources"
  match "futureproyectosactions/editresources"  => "futureproyectosactions#editresources"

  
  match "confirm/:token/:user_id/:user_token" => "panelcontrols#confirm_token"
 
  match "inlinepdf/users_confirm"  =>  "panelcontrols#usersconfirmpdf"

 

=begin
       match "proyectos/ordenby/:listby"  => "index", :controller => "proyectos"  
         member do
         get 'index'
         post 'index'
       end
=end 
 
 
 

  

  resources :roles

  resources :roles_users

root :to => "home#index"

end

app/models/cudidoc.rb
# encoding: UTF-8
class Cudidoc < ActiveRecord::Base
  
  before_save :make_parse
  before_create :make_parse
    def make_parse 
      string = self.contain.to_s
    end    
end

app/controllers/cudidocs_controller.rb
# coding: utf-8
class CudidocsController < ApplicationController

  skip_before_filter :only_authenticated_users_are_welcome, :except => [:datasheetsave, :getHtml, :publicdocs]

  def index
    @cudidocs = Cudidoc.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cudidocs }
    end
  end
  

  def datasheetsave

    respond_to do |format|
        
    if request.xhr?     

      vc=Cudidoc.find(params['fid']) if !params['fid']== ''       
      nui= params['fid'].gsub(/"/, '')                     

      buffer=''
      buffer = Hpricot.parse(params['contain'])
         
      local_filename=''
      directory_name = Rails.root.to_s  + '/'.to_s +  'usersdoc'.to_s
      Dir.mkdir(directory_name) unless File.exists?(directory_name)
      directory_user = Rails.root.to_s  + '/'.to_s + 'usersdoc'.to_s + '/'.to_s +  current_user.id.to_s
      Dir.mkdir(directory_user) unless File.exists?(directory_user)
          
      vra=''
      vra=  rand(35435234534534).to_s.chop 
                     
      if nui == ""         
        file_user_save =   vra.to_s + '.html'.to_s   if nui== ""
        c = Cudidoc.new(:namefile => 'new_file', :user_id => current_user.id,  :public => 'checked' )
        file_user = directory_user  + '/'.to_s +  vra.to_s  + '.html'.to_s
        c.update_attributes!(:contain =>   vra.to_s  + '.html'.to_s , :namefile => params['fn'])            
      end
          
      if params['fid'].to_i > 0 || nui.to_i > 0

        c =  Cudidoc.find_by_id_and_user_id(  nui  ,  current_user.id.to_s )
        if (c.nil?)
          file_user_save =   vra.to_s + '.html'.to_s   if nui== ""
          c = Cudidoc.new(:namefile => 'new_file', :user_id => current_user.id,  :public => 'checked' )
          file_user = directory_user  + '/'.to_s +  vra.to_s  + '.html'.to_s
          c.update_attributes!(:contain =>   vra.to_s  + '.html'.to_s , :namefile => params['fn'], :public => 'checked')
        else  
          c.update_attributes!(:contain =>   c.contain.to_s , :namefile => params['fn'], :public => 'checked')
          file_user = directory_user  + '/'.to_s +  c.contain.to_s
        end    
      end

      File.open(file_user, 'w') {|f| f.write(buffer) }
          
                     
      alldoc=Cudidoc.where(:user_id => current_user.id.to_s)

      format.js {render :partial => "datasheetsave", :locals => { :notice => 'el informe ha sido enviado', :shtml => c, :alldoc => alldoc }, :content_type => 'text/javascript'}
        else 
        end
    end  
  end  

  def getHtml
    v=Cudidoc.find(:first, :conditions=>{:id=> params['id']});
      respond_to do |format|
        if request.xhr?

          s=''        
          p =  Rails.root.to_s + '/'.to_s    +   'usersdoc'.to_s + '/'.to_s    + current_user.id.to_s + '/'.to_s + v.contain.to_s
          if !File.exist?(p)
            return false
          end
           
          handle = File.open(p,"r")
          handle.lines.each do |line|
            s += line.chomp 
          end
          handle.close

          v.contain = s
          v.contain = CGI::unescape(v.contain)
              
          alldoc=Cudidoc.where(:user_id => current_user.id.to_s)
          format.js {render :partial => "getHtml", :locals => { :notice => 'poner lo que proceda', :shtml => v, :alldoc => alldoc  }, :content_type => 'text/javascript'}
      end
    end      
  end


  def getalldocs
    respond_to do |format|
      if request.xhr?
        otheruserdoc=Cudidoc.find(:all, :conditions => "user_id <> " + current_user.id.to_s  + " AND public = 'checked'")
        alldoc=Cudidoc.where(:user_id => current_user.id.to_s)
          
        alldoc.each do |v|
          if (v.public.to_s != 'checked')
            v.public='false';
            v.user_id=User.find(:first).username
          end
        end     
        format.js {render :partial => "getalldocs", :locals => { :notice => 'poner lo que proceda',  :alldoc => alldoc, :otheruserdoc => otheruserdoc  }, :content_type => 'text/javascript'}
      end
    end    
  end



  def getallpublicdocs
    respond_to do |format|
      if request.xhr?     
        alldoc=Cudidoc.find(:all, :conditions => "public = 'false'")
               
        alldoc.each do |v|
          if (v.public.to_s != 'checked')
            v.public='false';
            v.user_id=User.find(:first).username
          end
        end
     
        format.js {render :partial => "getallpublicdocs", :locals => { :notice => 'poner lo que proceda',  :alldoc => alldoc  }, :content_type => 'text/javascript'}
      end
    end    
  end




  def erasedocs
    respond_to do |format|
      if request.xhr?
        a=params['myA']
        
        a.each do |v|
             
          s=v.split ','
          cd=Cudidoc.find(:first, :conditions => {:id => s});
          directory_user = Rails.root.to_s  + '/'.to_s + 'usersdoc'.to_s + '/'.to_s +  current_user.id.to_s
          file_user = directory_user  + '/' +  cd.contain.to_s.chop 
      
          File.delete(file_user) unless !File.exists?(file_user)                
          Cudidoc.delete(v.split ',')        
        end

        alldoc=Cudidoc.where(:user_id => current_user.id.to_s)
        alldoc.each do |v|
          if (v.public.to_s != 'checked')
            v.public='false';
          end
        end
                    
        format.js {render :partial => "getalldocs", :locals => { :notice => 'poner lo que proceda',  :alldoc => alldoc  }, :content_type => 'text/javascript'}
      end
    end   
  end


  def publicdocs
    respond_to do |format|
      if request.xhr?
        a=params['myA']        
        a= a[0]         
        a= a.split(',')

        a.each do |v|

          cd=Cudidoc.find(:first, :conditions => {:id => v });

          if (cd.public == 'checked')
            cd.update_attributes!(:public => 'false')
          else 
            cd.update_attributes!(:public => 'checked') 
          end
     
        end
        
        alldoc=Cudidoc.where(:user_id => current_user.id.to_s)
        alldoc.each do |v|
          if (v.public.to_s != 'checked')
            v.public='false';
          end
        end
       
        format.js {render :partial => "getalldocs", :locals => { :notice => 'poner lo que proceda',  :alldoc => alldoc  }, :content_type => 'text/javascript'}
      end
    end   
  end


  def sendpdf
  
    path=Rails.root.to_s+"/tmp/pdf/"
    Dir.mkdir(path,755) if !File.directory?(path)
  
    htm =  params['ht']
    asu =  params['asu']

    t = Time.now
    fe=t.strftime(" process:  %m/%d/%Y at %I:%M%p") 

    ac=0
    acs=''
    c=0

    htm.each_line do |line|  
      acs += line.to_s  if (c > 237)
      c += 1
    end

    acs = asu + acs + '<br>From  es.cudi.doc   cudi <br>'
 
    kit = PDFKit.new( acs ,  :orientation => 'Landscape', :header_spacing=>26, :footer_html => Rails.root.to_s+"/public/pdf/html/footer_pdf.html", 
                             :footer_line => true,   :header_html => Rails.root.to_s+"/public/pdf/html/header_pdf.html" )
    kit.stylesheets << 'public/stylesheets/jquery_sheet/jquery.sheet.css'
    kit.to_file(path.to_s + current_user.id.to_s + 'temporaluser.pdf') 
    
    fl=path.to_s + current_user.id.to_s + 'temporaluser.pdf'
  
  
    subject='cudi.es.doc' + current_user.email.to_s + ' from cudi ' + fe 
    body='The users: ' + current_user.email.to_s  +  ' send a file for you' 

    UserMailer.sendtmp_email_file(params['em'].to_s , fl , subject.to_s, body.to_s).deliver
  
      respond_to do |format|
        if request.xhr?
          format.js {render :partial => "sendpdf", :locals => { :notice => 'enviado correctamente' }, :content_type => 'text/javascript'}
        end
       end 
  
  end


  def updatetitles

    v=Cudidoc.find(:all, :conditions=>{:user_id=> current_user.id});
      respond_to do |format|
        if request.xhr?
          format.js {render :partial => "updatetitles", :locals => { :notice => 'poner lo que proceda', :shtml => v }, :content_type => 'text/javascript'}
        end
      end      

  end

  def show
    @cudidoc = Cudidoc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cudidoc }
    end
  end


  def new
    @cudidoc = Cudidoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cudidoc }
    end
  end


  def edit
    @cudidoc = Cudidoc.find(params[:id])
  end


  def create
    @cudidoc = Cudidoc.new(params[:cudidoc])

    respond_to do |format|
      if @cudidoc.save
        format.html { redirect_to @cudidoc, notice: 'Cudidoc was successfully created.' }
        format.json { render json: @cudidoc, status: :created, location: @cudidoc }
      else
        format.html { render action: "new" }
        format.json { render json: @cudidoc.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @cudidoc = Cudidoc.find(params[:id])

    respond_to do |format|
      if @cudidoc.update_attributes(params[:cudidoc])
        format.html { redirect_to @cudidoc, notice: 'Cudidoc was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cudidoc.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cudidoc = Cudidoc.find(params[:id])
    @cudidoc.destroy

    respond_to do |format|
      format.html { redirect_to cudidocs_url }
      format.json { head :ok }
    end
  end
  
  def enduserspreeadsheet
    respond_to do |format|
      if request.xhr?
        format.js {render :partial => "enduserspreeadsheet", :locals => { :notice => 'enviado correctamente', :shtml => 'aqui el fichero html' }, :content_type => 'text/javascript'}
      end
    end  
  end
  
end

app/helpers/cudidocs_helper.rb
module CudidocsHelper
  
def listmisdoc
  cudidoc=''
  cudidoc = Cudidoc.where(:user_id => current_user.id)
end  

def getHtml(id)
  cudidoc=''
  cudidoc = Cudidoc.find(id).contain
end  
  
end

app/views/cudidocs/_datasheetsave.js.erb
var nf='<%= shtml.id %>' ;

$("#fid").val(nf);

var s='<%= raw  shtml.contain %>';
$("#htmlcontain").val(s);
var fn = '<%= shtml.namefile %>';
$("#tempfn").val(fn);



/******está duplicado ***********************/


  $('#misdocumentos').html('<h2>Mis documentos</h2>');


  var tb="<div id='checkgroup'> <table><tr><td></td><td>Public</td></tr>";

  var ck='';
  var ckp='';
  var p='';
  var st='';

  <%  alldoc.each do |v| %>
    p='<%= v.public.to_s %>'; 
    if ( p  == 'checked'){
      p='checked';
    }else{
      p='';
    }

    ckp=   '<td><%= check_box_tag 'ckp_'+v.id.to_s , v.id.to_s,  ''  , :class => 'ckeckdoc', :checked => p  %></td><td>' + "</td>";

    ck= ck +  '<tr><td><%= check_box_tag 'ck_'+v.id.to_s , v.id.to_s, true, :class => 'ckeckdoc' %></td>' +  ckp +  '<td class="namefile">' + "<span  onclick='gdoc(<%= v.id.to_s %> );' id='" + <%= v.id.to_s %> + "'>" + <%= "'".to_s + v.namefile.to_s + "'".to_s %>  + "</span></td>";
    //st =  ck  + st ;
    

  <% end %>

  var lg= '</table><div><p>Con los elementos marcados:</p><a  onclick=erasedoc()' + ' > Borrar </a><a  onclick=publicdoc()' + ' > Hacer/no hacer público</a></div>';
 var sc= '<script> function erasedoc(){  var myA=new Array(); var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 sc = sc + ' var jqxhr = $.post("cudidocs/erasedocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';

 sc = sc + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

sc = sc + '</script>';


 var scp= '<script> function publicdoc(){  var myA=new Array(); var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 scp = scp + ' var jqxhr = $.post("cudidocs/publicdocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';

 scp = scp + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

scp = scp + '</script>';



 $('#misdocumentos').append(tb +  ck   + lg + sc + scp);

app/views/cudidocs/_enduserspreeadsheet.js.erb
var s='<%= raw  shtml %>';
host = '<%= request.host_with_port %>';

$('fullscreen').remove(); 
div = $("<div id='fullscreen' class='fullscreennada' style='align:top;'>").html(' ');
$("body").append(div);
$("#fullscreen").empty(); 

              $('#fullscreen').sheet({
                    title: 'Enduser Documentation <a href="#" onclick="jQuery.sheet.instance[1].toggleState(); return false;">EDIT</a>',
                    inlineMenu: inlineMenu($.sheet.instance), 
                    editable: false
                });

goToObj('#fullscreen');

app/views/cudidocs/_form.html.erb
<%= form_for(@cudidoc) do |f| %>
  <% if @cudidoc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cudidoc.errors.count, "error") %> prohibited this cudidoc from being saved:</h2>

      <ul>
      <% @cudidoc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :typedoc %><br />
    <%= f.text_field :typedoc %>
  </div>
  <div class="field">
    <%= f.label :namefile %><br />
    <%= f.text_field :namefile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cudidocs/_getHtml.js.erb
var s='<%= raw  shtml.contain %>';
$("#htmlcontain").val(s);
var nf='<%= shtml.id %>' ;
$("#fid").val(nf);
var fn = '<%= shtml.namefile %>';
$("#tempfn").val(fn);
$("#aopen").click();
$("#header").html(fn);
$('#minicio').click();

app/views/cudidocs/_getalldocs.js.erb
  $('#misdocumentos').html('<h2>Mis documentos</h2>');
  
  var tb="<div id='checkgroup'> <table><tr><td>T</td><td>Public</td></tr>";

  var ck='';
  var ckp='';
  var st='';

  <%  alldoc.each do |v| %>
    var ve='<%= v.public.to_s %>';
    if (!ve) ve='false';
    if ( ve  =='checked'){
      ckp=   '<td><%= image_tag("false.png", :size => "16x10", :alt => "Edit Entry") %></td><td>' + "</td>";
    }else{
       ckp=   '<td><%= image_tag("true.png", :size => "16x10", :alt => "Edit Entry") %></td><td>' + "</td>";
    }

    ck= ck +  '<tr><td><%= check_box_tag 'ck_'+v.id.to_s , v.id.to_s, true, :name => 'lecheck', :class => 'ckeckdoc' %></td>' +  ckp +  '<td>' + "<span class='namefile'  onclick='gdoc(<%= v.id.to_s %> );' id='" + <%= v.id.to_s %> + "'><a>" + <%= "'".to_s + v.namefile.to_s + "'".to_s %>  + "</a></span></td>";
    //st =  ck  + st ;
  <% end %>
     
  var lg= '</table><div><p>Con los elementos marcados:</p><a  onclick=erasedoc()' + ' > Borrar </a><a  onclick=publicdoc()' + ' > Hacer/no hacer público</a><p> <a onclick=sendpdf()> Enviar captura/pdf </a></p></div>';
 var sc= '<script> function erasedoc(){  var myA=new Array(); var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 sc = sc + ' var jqxhr = $.post("cudidocs/erasedocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';   
 
 sc = sc + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

sc = sc + '</script>';

 var scp= '<script> function publicdoc(){  var list=$("input[name*=' + "'lecheck'" + ']:checked");   var myA=new Array();    var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 scp = scp + ' var jqxhr = $.post("cudidocs/publicdocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';

 scp = scp + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

 scp = scp + '</script>';

 $('#misdocumentos').append(tb +  ck   + lg + sc + scp);

app/views/cudidocs/_getallpublicdocs.js.erb
  $('#documentospublicos').html('<h2>Documentos públicos</h2>');
  
  var tb="<div id='checkgroupalldocs'> <table><tr><td></td><td></td></tr>";

  var ck='';
  var ckp='';
  var st='';

  <%  alldoc.each do |v| %>
    var ve='<%= v.public.to_s %>';
    if (!ve) ve='false';
    if ( ve  =='checked'){
      //ckp=   '<td><%= check_box_tag 'ckp_'+v.id.to_s , v.id.to_s, true, :class => 'ckeckdoc' %></td><td>' + "</td>";
    }else{
      //ckp=   '<td><%= check_box_tag 'ckp_'+v.id.to_s , v.id.to_s, false, :class => 'ckeckdoc' %></td><td>' + "</td>";
    }

    ck= ck +  '<tr><td></td>' +  ckp +  '<td>' + "<span class='namefile'  onclick='gdoc(<%= v.id.to_s %> );' id='" + <%= v.id.to_s %> + "'><a>" + <%= "'".to_s + v.namefile.to_s + "'".to_s %>   + '</a>   by     <%= v.user_id.to_s %>'   +  "</span></td>";
    //st =  ck  + st ;
  <% end %>
     
  var lg= '</table>';
/*
 var sc= '<script> function erasedoc(){ alert("llega a erasedoc"); var myA=new Array(); var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 sc = sc + ' var jqxhr = $.post("cudidocs/erasedocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';   
 
 sc = sc + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

sc = sc + '</script>';


 var scp= '<script> function publicdoc(){ alert("llega a publicdoc"); var myA=new Array(); var c=0; $("#checkgroup :input:not(:checked)").each(function() { myA[c]=$(this).val();  c= c+1;  });';
 scp = scp + ' var jqxhr = $.post("cudidocs/publicdocs" ,"myA[]=" + myA ,  function(d) {  }) .success(function() {}).error(function() {}).complete(function() { })};';

 scp = scp + 'function askif(){ var app=""; app= apprise("Nombre de fichero",{"input":true}, function(r){ if(r){}});} ';

 scp = scp + '</script>';
*/
 $('#documentospublicos').append(tb +  ck   + lg  );
 //$('#misdocumentos').append('<script> function erasedoc(){ alert("llega a erasedoc"); $("#checkgroup :input:not(:checked)").each(function() { alert("hola mundo");  });}</script>');

app/views/cudidocs/_updatetitles.js.erb
alert('hola mundo');

app/views/cudidocs/edit.html.erb
<h1>Editing cudidoc</h1>

<%= render 'form' %>

<%= link_to 'Show', @cudidoc %> |
<%= link_to 'Back', cudidocs_path %>

app/views/cudidocs/new.html.erb
<h1>New cudidoc</h1>

<%= render 'form' %>

<%= link_to 'Back', cudidocs_path %>

app/views/cudidocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @cudidoc.user_id %>
</p>

<p>
  <b>Typedoc:</b>
  <%= @cudidoc.typedoc %>
</p>

<p>
  <b>Namefile:</b>
  <%= @cudidoc.namefile %>
</p>


<%= link_to 'Edit', edit_cudidoc_path(@cudidoc) %> |
<%= link_to 'Back', cudidocs_path %>