config/routes.rb
Cudi::Application.routes.draw do

  resources :cudidocs
  resources :pictures
  resources :filesuploads
   resources :photos, :only => [:create, :destroy]

  
  

devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :passwords => 'passwords' 
} do
  post '/users/sign_in' => 'sessions#create' 
  get  '/users/sign_out' => 'devise/sessions#destroy' 
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  
  resources :users

  resources :priorities

  resources :resources
  
  resources :proyectostatuses

  resources :historics

  resources :documents

  resources :uploads

  resources :panelcontrols, :path_names => { :update => 'updateroles' } 

	
  

 

  resources :panelcontrols,:only => [:generate_document] do
     collection do
       post "generate_document"
     end
   end

  resources :proyectos,:only => [:index] do
     collection do
       post "post_data"
     end
   end

  resources :proyectos,:only => [:editresources] do
     collection do
       post "editresources"
     end
   end

  resources :proyectos,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

  

  resources :proyectos,:only => [:new] do
     collection do
     end
   end

  resources :proyectos,:only => [:setg] do
     collection do
       post "setg"
     end
  end
   
   
  resources :proyectos,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
  end
   

   

  resources :proyectos,:only => [:list_proyect_iphone] do
     collection do
       post "list_proyect_iphone"
     end
   end
   
   

 

  resources :proyectos,:only => [:mobile_new_proyecto] do
     collection do
       get "mobile_new_proyecto"
       post "mobile_new_proyecto"
     end
   end
   

  resources :futureproyectos,:only => [:index] do
     collection do
       post "post_data_futureproyectos"
     end
   end
  
=begin
  resources :futureproyectos,:only => [:editresources] do
     collection do
       post "post_data_futureproyectosedit"
     end
  end
=end  

 
   
     resources :futureproyectosactions,:only => [:setg] do
     collection do
       post "setg"
     end
   end

  resources :proyectos,:only => [:pickupfile] do
     collection do
       post "pickupfile"
     end
   end
   

   

  resources :futureproyectosactions,:only => [:index] do
     collection do
       post "post_data_futureproyectosactions"
     end
   end
   
   
   resources :futureproyectosactions,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
    end
    
      resources :futureproyectosactions,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

   resources :cudidocs,:only => [:datasheetsave] do
     collection do
       post "datasheetsave"
     end
    end

   resources :cudidocs,:only => [:getHtml] do
     collection do
       post "getHtml"
     end
    end

   resources :cudidocs,:only => [:updatetitles] do
     collection do
       post "updatetitles"
     end
    end
    
    resources :cudidocs,:only => [:getalldocs] do
     collection do
       post "getalldocs"
     end
    end
    
    
    
    resources :cudidocs,:only => [:getallpublicdocs] do
     collection do
       post "getallpublicdocs"
     end
    end
    
    
    
    
       resources :cudidocs,:only => [:erasedocs] do
     collection do
       post "erasedocs"
     end
    end
    
     resources :cudidocs,:only => [:publicdocs] do
     collection do
       post "publicdocs"
     end
    end
    
     resources :cudidocs,:only => [:sendpdf] do
     collection do
       post "sendpdf"
     end
    end    
    
    
     resources :cudidocs,:only => [:enduserspreeadsheet] do
     collection do
       post "enduserspreeadsheet"
     end
    end   
     
    
    
    
    
    resources :users,:only => [:usersonline] do
         collection do
       post "usersonline"
     end
    end  
    
    
    
    

  
   match "listpdffiles" => "home#listpdffiles"
   match "showpdf" => "home#showpdf"
   
   match "cudidocs/getHtml/:docid" => "cudidocs#getHtml" 
   
   match "cudidocs/updatetitles/:noid" => "cudidocs#updatetitles"

  
  
  match "publicproyecto/:proyectotitle" => "publicproyecto#index" 
  
 
  
  match "sendpdftousers" => "panelcontrols#sendpdftousers"  
  match "create_pdf" => "panelcontrols#create_pdf" 
  match "proyectos/status/:status_id/resource/:resource_id" => "proyectos#index"
  match "futureproyectosactions/status/:status_id/resource/:resource_id" => "futureproyectosactions#index"
  
 
  match "futureproyectos/getresources"  => "futureproyectos#getresources"
  match "proyectos/publicos/:parent_id"  => "proyectos#proyectourl"
  match "proyectos/editresources/:parent_id"  => "proyectos#editresources"
  match "futureproyectos/editresources"  => "futureproyectos#editresources"
  match "futureproyectosactions/editresources"  => "futureproyectosactions#editresources"

  
  match "confirm/:token/:user_id/:user_token" => "panelcontrols#confirm_token"
 
  match "inlinepdf/users_confirm"  =>  "panelcontrols#usersconfirmpdf"

 

=begin
       match "proyectos/ordenby/:listby"  => "index", :controller => "proyectos"  
         member do
         get 'index'
         post 'index'
       end
=end 
 
 
 

  

  resources :roles

  resources :roles_users

root :to => "home#index"

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proyectoid %><br />
    <%= f.text_field :proyectoid %>
  </div>
  <div class="field">
    <%= f.label :resource %><br />
    <%= f.text_field :resource %>
  </div>
  <div class="field">
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Proyectoid</th>
    <th>Resource</th>
    <th>Controller</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.proyectoid %></td>
    <td><%= resource.resource %></td>
    <td><%= resource.controller %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proyectoid:</b>
  <%= @resource.proyectoid %>
</p>

<p>
  <b>Resource:</b>
  <%= @resource.resource %>
</p>

<p>
  <b>Controller:</b>
  <%= @resource.controller %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>