config/routes.rb
Cudi::Application.routes.draw do

  resources :cudidocs
  resources :pictures
  resources :filesuploads
   resources :photos, :only => [:create, :destroy]

  
  

devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :passwords => 'passwords' 
} do
  post '/users/sign_in' => 'sessions#create' 
  get  '/users/sign_out' => 'devise/sessions#destroy' 
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
end

  
  resources :users

  resources :priorities

  resources :resources
  
  resources :proyectostatuses

  resources :historics

  resources :documents

  resources :uploads

  resources :panelcontrols, :path_names => { :update => 'updateroles' } 

	
  

 

  resources :panelcontrols,:only => [:generate_document] do
     collection do
       post "generate_document"
     end
   end

  resources :proyectos,:only => [:index] do
     collection do
       post "post_data"
     end
   end

  resources :proyectos,:only => [:editresources] do
     collection do
       post "editresources"
     end
   end

  resources :proyectos,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

  

  resources :proyectos,:only => [:new] do
     collection do
     end
   end

  resources :proyectos,:only => [:setg] do
     collection do
       post "setg"
     end
  end
   
   
  resources :proyectos,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
  end
   

   

  resources :proyectos,:only => [:list_proyect_iphone] do
     collection do
       post "list_proyect_iphone"
     end
   end
   
   

 

  resources :proyectos,:only => [:mobile_new_proyecto] do
     collection do
       get "mobile_new_proyecto"
       post "mobile_new_proyecto"
     end
   end
   

  resources :futureproyectos,:only => [:index] do
     collection do
       post "post_data_futureproyectos"
     end
   end
  
=begin
  resources :futureproyectos,:only => [:editresources] do
     collection do
       post "post_data_futureproyectosedit"
     end
  end
=end  

 
   
     resources :futureproyectosactions,:only => [:setg] do
     collection do
       post "setg"
     end
   end

  resources :proyectos,:only => [:pickupfile] do
     collection do
       post "pickupfile"
     end
   end
   

   

  resources :futureproyectosactions,:only => [:index] do
     collection do
       post "post_data_futureproyectosactions"
     end
   end
   
   
   resources :futureproyectosactions,:only => [:udateFromTinymce] do
     collection do
       post "udateFromTinymce"
     end
    end
    
      resources :futureproyectosactions,:only => [:getresources] do
     collection do
       get "getresources"
     end
    end 

   resources :cudidocs,:only => [:datasheetsave] do
     collection do
       post "datasheetsave"
     end
    end

   resources :cudidocs,:only => [:getHtml] do
     collection do
       post "getHtml"
     end
    end

   resources :cudidocs,:only => [:updatetitles] do
     collection do
       post "updatetitles"
     end
    end
    
    resources :cudidocs,:only => [:getalldocs] do
     collection do
       post "getalldocs"
     end
    end
    
    
    
    resources :cudidocs,:only => [:getallpublicdocs] do
     collection do
       post "getallpublicdocs"
     end
    end
    
    
    
    
       resources :cudidocs,:only => [:erasedocs] do
     collection do
       post "erasedocs"
     end
    end
    
     resources :cudidocs,:only => [:publicdocs] do
     collection do
       post "publicdocs"
     end
    end
    
     resources :cudidocs,:only => [:sendpdf] do
     collection do
       post "sendpdf"
     end
    end    
    
    
     resources :cudidocs,:only => [:enduserspreeadsheet] do
     collection do
       post "enduserspreeadsheet"
     end
    end   
     
    
    
    
    
    resources :users,:only => [:usersonline] do
         collection do
       post "usersonline"
     end
    end  
    
    
    
    

  
   match "listpdffiles" => "home#listpdffiles"
   match "showpdf" => "home#showpdf"
   
   match "cudidocs/getHtml/:docid" => "cudidocs#getHtml" 
   
   match "cudidocs/updatetitles/:noid" => "cudidocs#updatetitles"

  
  
  match "publicproyecto/:proyectotitle" => "publicproyecto#index" 
  
 
  
  match "sendpdftousers" => "panelcontrols#sendpdftousers"  
  match "create_pdf" => "panelcontrols#create_pdf" 
  match "proyectos/status/:status_id/resource/:resource_id" => "proyectos#index"
  match "futureproyectosactions/status/:status_id/resource/:resource_id" => "futureproyectosactions#index"
  
 
  match "futureproyectos/getresources"  => "futureproyectos#getresources"
  match "proyectos/publicos/:parent_id"  => "proyectos#proyectourl"
  match "proyectos/editresources/:parent_id"  => "proyectos#editresources"
  match "futureproyectos/editresources"  => "futureproyectos#editresources"
  match "futureproyectosactions/editresources"  => "futureproyectosactions#editresources"

  
  match "confirm/:token/:user_id/:user_token" => "panelcontrols#confirm_token"
 
  match "inlinepdf/users_confirm"  =>  "panelcontrols#usersconfirmpdf"

 

=begin
       match "proyectos/ordenby/:listby"  => "index", :controller => "proyectos"  
         member do
         get 'index'
         post 'index'
       end
=end 
 
 
 

  

  resources :roles

  resources :roles_users

root :to => "home#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates_presence_of  :title, :description, :file
  mount_uploader :file, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pictures }
    end
  end

  def show
    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  def new
    @picture = Picture.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @picture }
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def create
    @picture = Picture.new(params[:picture])
    respond_to do |format|
      if @picture.save
        format.html { redirect_to(@picture, :notice => 'Picture was successfully created.') }
        format.xml  { render :xml => @picture, :status => :created, :location => @picture }
        format.json {  render :json => { :pic_path => @picture.file.url(:thumb).to_s, :name => @picture.file.filename }, 
                                         :content_type => 'text/html'
                    }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
        format.json { render :json => { :result => 'error'}, 
                             :content_type => 'text/html'
                    }
      end
    end
  end

  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to(@picture, :notice => 'Picture was successfully updated.') }
        format.xml  { head :ok }
        format.json {  render :json => { :pic_path => @picture.file.url(:thumb).to_s, :name => @picture.file.filename }, 
                              :content_type => 'text/html'
                    }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @picture.errors, :status => :unprocessable_entity }
        format.json { render :json => { :result => 'error'}, 
                             :content_type => 'text/html'
                    }
      end
    end
  end


  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to(pictures_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="bodyForm">
  <%= form_for @picture, :html => {:multipart => true, :id => "file_upload"}, :validate => true do |f| %>
  <% if @picture.errors.any? %>
    <p id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <p class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,:rows => 8, :cols => 40 %>
  </p>
  
  <p id="picture_placeholder">
    <% if @picture.file? %>
    <p>
      <%= image_tag(@picture.file_url(:medium)) %>
    </p>
    <% end %>
  </p>

  <p id="file_upload_container">
    <%= f.file_field :file, :class =>'file_upload_browse' %>     
      <button>Enviar</button>
  </p>
    <% end %>
</div>
<table id="files"></table>

app/views/pictures/edit.html.erb
<h1>Editar im&aacute;genes</h1>

<div class="actions">
  <%= link_to 'Volver', pictures_path %>
  <%= link_to 'Previsualizar', @picture %>
</div>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>Listado de im&aacute;genes</h1>

<table class="listadoImagenes">
  <tr>
    <th>T&iacute;tulo</th>
    <th>Descripci&oacute;n</th>
    <th>Archivo</th>
    <th class="PEE"></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.title %></td>
    <td><%= picture.description %></td>
    <td><%= image_tag(picture.file_url(:thumb)) if picture.file.present? %></td>
    <td><%= link_to 'Previsualizar', picture %>    <%= link_to 'Editar', edit_picture_path(picture) %>    <%= link_to 'Eliminar', picture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Nueva imagen',new_picture_path, :id => 'nuevaimagen' %>


<p onClick="alert(ed.windowManager.new_variable)"></p>

app/views/pictures/new.html.erb
<h1>A&ntilde;adir imagen</h1>

<div class="actions"><%= link_to '<< Volver', pictures_path %></div>

<%= render 'form' %>

<p id="file_upload_container">
  <button id="fakeinputbrowser" onClick="javascript:document.getElementById('picture_file').click();">
    Localizar Imagen
  </button>
</p>

app/views/pictures/show.html.erb
<div class="actions">
	<%= link_to 'Volver', pictures_path %>
	<%= link_to 'Editar', edit_picture_path(@picture) %> 
</div>

<div class="bodyForm">
<p id="notice"><%= notice %></p>

<p>
  <b>T&iacute;tulo:</b>
  <%= @picture.title %>
</p>

<p>
  <b>Descripci&oacute;n:</b>
  <%= @picture.description %>
</p>

<p>
  <b>Archivo:</b>
  <%= image_tag(@picture.file_url(:medium)) %>
</p>


</div>